import type { PrintableInput } from '@/types/printable'
import { normalizePrintable } from '@/types/printable'

function daysAgo(days: number) {
  return new Date(Date.now() - days * 86_400_000).toISOString()
}

const now = new Date().toISOString()

const DEMO_ROWS: PrintableInput[] = [
  {
    id: 'demo-dino',
    title: '티라노 색칠공부',
    category: 'coloring',
    tags: ['공룡', '티라노', '유치원', '5-7세'],
    color_image_url: '/samples/dino-color.svg',
    line_art_url: '/samples/dino-line.svg',
    pdf_url: '/samples/dino-line.svg',
    views: 2410,
    downloads: 1284,
    created_at: now,
  },
  {
    id: 'demo-maze',
    title: '공룡 알 미로찾기',
    category: 'maze',
    tags: ['미로', '공룡', '두뇌놀이', '중급', '4-6세'],
    color_image_url: '/samples/maze-color.svg',
    line_art_url: '/samples/maze-line.svg',
    pdf_url: '/samples/maze-line.svg',
    views: 1860,
    downloads: 942,
    created_at: now,
  },
  {
    id: 'demo-lion',
    title: '햇살 사자',
    category: 'coloring',
    tags: ['동물', '사자', '초급', '유아', '2-4세', '3-5세'],
    color_image_url: '/samples/lion-color.svg',
    line_art_url: '/samples/lion-line.svg',
    pdf_url: '/samples/lion-line.svg',
    views: 1640,
    downloads: 811,
    created_at: now,
  },
  {
    id: 'demo-abc',
    title: '알파벳 A-Z 따라쓰기',
    category: 'alphabet',
    tags: ['알파벳', '학습지', '유치원', '5-7세', '따라쓰기'],
    color_image_url: '/samples/abc-color.svg',
    line_art_url: '/samples/abc-line.svg',
    pdf_url: '/samples/abc-line.svg',
    views: 2211,
    downloads: 1099,
    created_at: now,
  },
  {
    id: 'demo-rocket',
    title: '우주 로켓 색칠',
    category: 'coloring',
    tags: ['우주', '로켓', '중급', '4-6세'],
    color_image_url: '/samples/rocket-color.svg',
    line_art_url: '/samples/rocket-line.svg',
    pdf_url: '/samples/rocket-line.svg',
    views: 980,
    downloads: 512,
    created_at: now,
  },
  {
    id: 'demo-star',
    title: '별 따라그리기',
    category: 'tracing',
    tags: ['점잇기', '도형', '유아', '2-4세', '초급', '3-5세', '선따기', '소근육'],
    color_image_url: '/samples/star-color.svg',
    line_art_url: '/samples/star-line.svg',
    pdf_url: '/samples/star-line.svg',
    views: 740,
    downloads: 388,
    created_at: now,
  },
  {
    id: 'demo-princess',
    title: '숲속 공주 색칠공부',
    category: 'coloring',
    tags: ['공주', '판타지', '요정', '4-6세'],
    color_image_url: '/samples/princess-color.svg',
    line_art_url: '/samples/princess-line.svg',
    pdf_url: '/samples/princess-line.svg',
    views: 1330,
    downloads: 701,
    created_at: now,
  },
  {
    id: 'demo-car',
    title: '꼬마 자동차 색칠',
    category: 'coloring',
    tags: ['자동차', '탈것', '유아', '2-4세', '3-5세'],
    color_image_url: '/samples/car-color.svg',
    line_art_url: '/samples/car-line.svg',
    pdf_url: '/samples/car-line.svg',
    views: 1190,
    downloads: 640,
    created_at: daysAgo(2),
  },
  {
    id: 'demo-fire',
    title: '용감한 소방차',
    category: 'coloring',
    tags: ['탈것', '자동차', '소방차', '구급차', '4-6세'],
    color_image_url: '/samples/fire-color.svg',
    line_art_url: '/samples/fire-line.svg',
    pdf_url: '/samples/fire-line.svg',
    views: 1540,
    downloads: 880,
    created_at: daysAgo(1),
  },
  {
    id: 'demo-police',
    title: '출동 경찰차',
    category: 'coloring',
    tags: ['탈것', '자동차', '경찰차', '4-6세'],
    color_image_url: '/samples/police-color.svg',
    line_art_url: '/samples/police-line.svg',
    pdf_url: '/samples/police-line.svg',
    views: 1320,
    downloads: 710,
    created_at: daysAgo(4),
  },
  {
    id: 'demo-excavator',
    title: '힘센 포크레인',
    category: 'coloring',
    tags: ['탈것', '중장비', '포크레인', '4-6세'],
    color_image_url: '/samples/excavator-color.svg',
    line_art_url: '/samples/excavator-line.svg',
    pdf_url: '/samples/excavator-line.svg',
    views: 990,
    downloads: 540,
    created_at: daysAgo(6),
  },
  {
    id: 'demo-sports',
    title: '빨간 스포츠카',
    category: 'coloring',
    tags: ['탈것', '자동차', '스포츠카', '5-7세'],
    color_image_url: '/samples/sports-color.svg',
    line_art_url: '/samples/sports-line.svg',
    pdf_url: '/samples/sports-line.svg',
    views: 1110,
    downloads: 620,
    created_at: daysAgo(3),
  },
  {
    id: 'demo-plane',
    title: '하늘 비행기',
    category: 'coloring',
    tags: ['탈것', '비행기', '기차', '3-5세'],
    color_image_url: '/samples/plane-color.svg',
    line_art_url: '/samples/plane-line.svg',
    pdf_url: '/samples/plane-line.svg',
    views: 870,
    downloads: 430,
    created_at: daysAgo(5),
  },
  {
    id: 'demo-ispy',
    title: '숲속 숨은그림찾기 I Spy',
    category: 'maze',
    tags: ['숨은그림', 'I Spy', '관찰력', '집중력', '두뇌놀이', '4-6세'],
    color_image_url: '/samples/lion-color.svg',
    line_art_url: '/samples/lion-line.svg',
    pdf_url: '/samples/lion-line.svg',
    views: 1260,
    downloads: 690,
    created_at: daysAgo(2),
  },
  {
    id: 'demo-odd-one',
    title: '다른하나찾기 동물 편',
    category: 'maze',
    tags: ['다른하나', '관찰력', '집중력', '두뇌놀이', '3-5세'],
    color_image_url: '/samples/dino-color.svg',
    line_art_url: '/samples/dino-line.svg',
    pdf_url: '/samples/dino-line.svg',
    views: 980,
    downloads: 510,
    created_at: daysAgo(3),
  },
  {
    id: 'demo-shadow',
    title: '그림자맞추기 탈것',
    category: 'maze',
    tags: ['그림자', '사고력', '관찰력', '두뇌놀이', '4-6세'],
    color_image_url: '/samples/car-color.svg',
    line_art_url: '/samples/car-line.svg',
    pdf_url: '/samples/car-line.svg',
    views: 860,
    downloads: 440,
    created_at: daysAgo(4),
  },
  {
    id: 'demo-sequence',
    title: '하루 일과 순서배열',
    category: 'numbers',
    tags: ['순서배열', '사고력', '지구력', '두뇌놀이', '5-7세'],
    color_image_url: '/samples/abc-color.svg',
    line_art_url: '/samples/abc-line.svg',
    pdf_url: '/samples/abc-line.svg',
    views: 720,
    downloads: 360,
    created_at: daysAgo(5),
  },
  {
    id: 'demo-routine',
    title: '아침 루틴 체크차트',
    category: 'tracing',
    tags: ['루틴', '아침', '아침루틴', '생활습관', '부모함께', '3-5세'],
    color_image_url: '/samples/star-color.svg',
    line_art_url: '/samples/star-line.svg',
    pdf_url: '/samples/star-line.svg',
    views: 1580,
    downloads: 820,
    created_at: daysAgo(1),
  },
  {
    id: 'demo-emotion',
    title: '감정 매칭카드',
    category: 'tracing',
    tags: ['감정', 'SEL', '감정표현', '부모함께', '4-6세'],
    color_image_url: '/samples/princess-color.svg',
    line_art_url: '/samples/princess-line.svg',
    pdf_url: '/samples/princess-line.svg',
    views: 1410,
    downloads: 760,
    created_at: daysAgo(2),
  },
  {
    id: 'demo-puppets',
    title: '동물 손가락인형',
    category: 'tracing',
    tags: ['손가락인형', '부모함께', '역할놀이', '3-5세'],
    color_image_url: '/samples/lion-color.svg',
    line_art_url: '/samples/lion-line.svg',
    pdf_url: '/samples/lion-line.svg',
    views: 640,
    downloads: 310,
    created_at: daysAgo(6),
  },
  {
    id: 'demo-board',
    title: '한장 보드게임 가족놀이',
    category: 'maze',
    tags: ['보드게임', '부모함께', '가족', '5-7세'],
    color_image_url: '/samples/maze-color.svg',
    line_art_url: '/samples/maze-line.svg',
    pdf_url: '/samples/maze-line.svg',
    views: 910,
    downloads: 470,
    created_at: daysAgo(3),
  },
]

const TITLE_EN: Record<string, string> = {
  'demo-dino': 'T-Rex Coloring Page',
  'demo-maze': 'Dinosaur Egg Maze',
  'demo-lion': 'Sunny Lion',
  'demo-abc': 'Alphabet A-Z Tracing',
  'demo-rocket': 'Space Rocket Coloring',
  'demo-star': 'Star Tracing',
  'demo-princess': 'Forest Princess Coloring',
  'demo-car': 'Little Car Coloring',
  'demo-fire': 'Brave Fire Truck',
  'demo-police': 'Police Car Dispatch',
  'demo-excavator': 'Mighty Excavator',
  'demo-sports': 'Red Sports Car',
  'demo-plane': 'Sky Airplane',
  'demo-ispy': 'Forest I Spy',
  'demo-odd-one': 'Odd One Out Animals',
  'demo-shadow': 'Vehicle Shadow Match',
  'demo-sequence': 'Daily Routine Sequence',
  'demo-routine': 'Morning Routine Chart',
  'demo-emotion': 'Emotion Matching Cards',
  'demo-puppets': 'Animal Finger Puppets',
  'demo-board': 'One-Page Family Board Game',
}

export const DEMO_PRINTABLES = DEMO_ROWS.map((row) =>
  normalizePrintable({
    ...row,
    slug: row.slug || row.id,
    title_ko: row.title_ko || row.title,
    title_en: TITLE_EN[row.id] || row.title_en || row.title,
    image_bw_url: row.image_bw_url || row.line_art_url,
    image_color_url: row.image_color_url || row.color_image_url,
  }),
)
