export type SupportedLang = 'ko' | 'en' | 'ja' | 'zh' | 'es' | 'pt' | 'de' | 'fr' | 'it' | 'vi'

export interface LocalizedText {
  ko: string
  en: string
  ja: string
  zh: string
  es: string
  pt: string
  de: string
  fr: string
  it: string
  vi: string
}

export interface AffiliateItem {
  id: string
  image: string
  badge: LocalizedText
  headline: LocalizedText
  painPoint: LocalizedText
  benefit1: LocalizedText
  benefit2: LocalizedText
  ctaText: LocalizedText
  coupangUrl: string
  amazonUrl: string
}

export const AFFILIATE_GUIDE_TITLE: LocalizedText = {
  ko: '이런 점을 확인해보세요',
  en: 'Look for these details',
  ja: 'こんなポイントを確認してみてください',
  zh: '可以先確認這些重點',
  es: 'Revisa estos detalles',
  pt: 'Confira estes pontos',
  de: 'Achten Sie auf diese Punkte',
  fr: 'Vérifiez ces points',
  it: 'Controlla questi dettagli',
  vi: 'Hãy chú ý những điểm này',
}

export const AFFILIATE_ITEMS: AffiliateItem[] = [
  {
    id: '01_crayons',
    image: '/affiliate/affiliate_01_crayons.webp',
    badge: {
      ko: "✨ DOOLIA'S PICK",
      en: "✨ DOOLIA'S PICK",
      ja: "✨ DOOLIA'S PICK",
      zh: '✨ DOOLIA 精選',
      es: '✨ SELECCIÓN DOOLIA',
      pt: '✨ ESCOLHA DOOLIA',
      de: '✨ DOOLIA EMPFEHLUNG',
      fr: '✨ SÉLECTION DOOLIA',
      it: '✨ SCELTO DA DOOLIA',
      vi: '✨ LỰA CHỌN DOOLIA',
    },
    headline: {
      ko: '손이나 벽에 묻어도 물로 쏙 지워지는 안심 크레용',
      en: 'Ultra-Clean Washable Crayons for Toddlers',
      ja: '手や壁についても水で落とせる安心クレヨン',
      zh: '沾到手上或牆壁也能用水輕鬆擦拭的安心蠟筆',
      es: 'Crayones lavables seguros que se limpian con agua',
      pt: 'Gizes de cera laváveis e seguros que saem com água',
      de: 'Leicht abwaschbare Wachsmalstifte für Kleinkinder',
      fr: 'Craies de coloriage ultra-lavables et sûres pour tout-petits',
      it: 'Pastelli a cera ultra lavabili e sicuri per bambini',
      vi: 'Sáp màu an toàn, dễ dàng tẩy rửa bằng nước cho bé',
    },
    painPoint: {
      ko: '손이나 옷, 벽에 낙서할까 봐 불안하셨나요?',
      en: 'Worried about messy crayon marks on hands, clothes, or walls?',
      ja: '手や服、壁の落書き汚れが心配ではありませんか？',
      zh: '擔心孩子畫到手上、衣服或牆壁上難以清理嗎？',
      es: '¿Te preocupan las manchas de crayón en manos, ropa o paredes?',
      pt: 'Preocupado com manchas de giz nas mãos, roupas ou paredes?',
      de: 'Sorge vor Flecken an Händen, Kleidung oder Wänden?',
      fr: 'Peur des taches de craie sur les mains, les vêtements ou les murs ?',
      it: 'Preoccupato per i segni di pastello su mani, vestiti o pareti?',
      vi: 'Bạn lo lắng vết sáp màu dính vào tay, quần áo hay tường?',
    },
    benefit1: {
      ko: '물과 비누로 말끔하게 세척되는 이지 워셔블',
      en: 'Easily washes from skin and most fabrics with warm water',
      ja: '水や石鹸ですっきり落とせるイージーウォッシャブル',
      zh: '用肥皂和溫水即可輕鬆洗淨的超易水洗配方',
      es: 'Se limpia fácilmente de la piel y telas con agua y jabón',
      pt: 'Sai facilmente da pele e tecidos com água e sabão',
      de: 'Lässt sich leicht mit Wasser und Seife von Haut und Kleidung reinigen',
      fr: 'Se nettoie facilement de la peau et des vêtements à l’eau',
      it: 'Si lava via facilmente da pelle e vestiti con acqua e sapone',
      vi: 'Dễ dàng rửa sạch khỏi da và quần áo chỉ bằng nước xà phòng',
    },
    benefit2: {
      ko: '구강기 안심 무독성 원료 & 단단한 부러짐 방지',
      en: '100% Non-toxic safe formula with break-resistant design',
      ja: 'なめても安全な無毒性原料＆折れにくい丈夫な設計',
      zh: '無毒安全成份，堅固不易折斷',
      es: 'Fórmula no tóxica y diseño resistente a roturas',
      pt: 'Fórmula atóxica segura e resistente a quebras',
      de: 'Ungiftige, sichere Inhaltsstoffe und bruchfestes Design',
      fr: 'Formule non toxique et corps ultra-résistant aux chutes',
      it: 'Formula atossica e sicura con corpo resistente alle rotture',
      vi: 'Thành phần không độc hại, thân bút cứng cáp khó gãy',
    },
    ctaText: {
      ko: '물로 쉽게 닦이는 안심 크레용 둘러보기 ↗',
      en: 'View Safe Washable Crayons ↗',
      ja: '水で落とせる安心クレヨンを見る ↗',
      zh: '查看水洗安心蠟筆 ↗',
      es: 'Ver crayones lavables recomendados ↗',
      pt: 'Ver gizes de cera laváveis ↗',
      de: 'Abwaschbare Wachsmalstifte ansehen ↗',
      fr: 'Découvrir les craies lavables ↗',
      it: 'Scopri i pastelli lavabili ↗',
      vi: 'Xem sáp màu an toàn dễ rửa ↗',
    },
    coupangUrl:
      'https://www.coupang.com/np/search?component=&q=%EC%9C%A0%EC%95%84+%EC%9B%8C%EC%85%94%EB%B8%94+%ED%81%AC%EB%A0%88%EC%9A%A9',
    amazonUrl: 'https://www.amazon.com/s?k=Washable+Crayons+for+Toddlers',
  },
  {
    id: '02_colored_pencils',
    image: '/affiliate/affiliate_02_colored_pencils.webp',
    badge: {
      ko: "✨ DOOLIA'S PICK",
      en: "✨ DOOLIA'S PICK",
      ja: "✨ DOOLIA'S PICK",
      zh: '✨ DOOLIA 精選',
      es: '✨ SELECCIÓN DOOLIA',
      pt: '✨ ESCOLHA DOOLIA',
      de: '✨ DOOLIA EMPFEHLUNG',
      fr: '✨ SÉLECTION DOOLIA',
      it: '✨ SCELTO DA DOOLIA',
      vi: '✨ LỰA CHỌN DOOLIA',
    },
    headline: {
      ko: '손 힘이 약한 아이를 위한 맞춤 삼각 점보 색연필',
      en: 'Jumbo Triangular Colored Pencils for Easy Grip',
      ja: '握力の弱いお子様のための三角ジャンボ色鉛筆',
      zh: '專為小手力量不足設計的粗桿三角彩色鉛筆',
      es: 'Lápices de colores triangulares jumbo para un fácil agarre',
      pt: 'Lápis de cor triangulares jumbo para pegada confortável',
      de: 'Jumbo Dreikant-Buntstifte für kleine Kinderhände',
      fr: 'Crayons de couleur triangulaires jumbo faciles à tenir',
      it: 'Matite colorate triangolari jumbo per una presa facile',
      vi: 'Bút chì màu tam giác thân to trợ lực cho bé',
    },
    painPoint: {
      ko: '색칠하다가 금방 손가락이 아프다고 멈추나요?',
      en: 'Does your child tire quickly from gripping thin pencils?',
      ja: '塗り絵の途中で手が疲れてやめてしまいませんか？',
      zh: '孩子畫沒多久就抱怨手痠握不住筆嗎？',
      es: '¿Tu peque se cansa rápido de sujetar lápices delgados?',
      pt: 'Seu filho se cansa rápido segurando lápis finos?',
      de: 'Ermüden die Finger Ihres Kindes schnell beim Malen?',
      fr: 'Votre enfant se fatigue-t-il vite avec des crayons trop fins ?',
      it: 'Il tuo bambino si stanca subito impugnando matite sottili?',
      vi: 'Bé có thường mỏi tay và bỏ dở khi tô màu không?',
    },
    benefit1: {
      ko: '바른 연필잡기를 자연스럽게 유도하는 인체공학 삼각 그립',
      en: 'Ergonomic triangular shape naturally guides proper grip',
      ja: '正しい鉛筆の持ち方を自然に育てる人間工学三角グリップ',
      zh: '人體工學三角筆桿，自然引導正確握筆姿勢',
      es: 'Forma triangular ergonómica para un agarre correcto natural',
      pt: 'Design triangular ergonômico que ajuda na pegada correta',
      de: 'Ergonomische Dreikantform für die richtige Stifthaltung',
      fr: 'Forme triangulaire ergonomique guidant la bonne prise en main',
      it: 'Forma triangolare ergonomica per imparare a impugnare bene',
      vi: 'Thân bút tam giác công thái học giúp bé cầm bút chuẩn',
    },
    benefit2: {
      ko: '적은 힘으로도 부드럽고 선명하게 칠해지는 점보 심',
      en: 'Thick, smooth lead delivers vibrant colors with minimal effort',
      ja: '弱い力でも滑らかで鮮やかに発色する太芯設計',
      zh: '加粗筆芯，輕輕一畫即可顯現鮮豔色彩',
      es: 'Mina gruesa y suave que pinta con colores vivos sin esfuerzo',
      pt: 'Mina grossa e macia com cores vibrantes sem esforço',
      de: 'Dicke, weiche Mine für leuchtende Farben ohne viel Druck',
      fr: 'Mine épaisse et douce offrant des couleurs vives sans forcer',
      it: 'Mina spessa e morbida per colori vivaci con poco sforzo',
      vi: 'Ngòi to mềm mại, tô màu đậm nét chỉ với lực nhẹ',
    },
    ctaText: {
      ko: '손이 편한 삼각 점보 색연필 둘러보기 ↗',
      en: 'View Jumbo Triangular Pencils ↗',
      ja: '手が疲れない三角ジャンボ色鉛筆を見る ↗',
      zh: '查看省力三角粗桿色鉛筆 ↗',
      es: 'Ver lápices triangulares jumbo ↗',
      pt: 'Ver lápis de cor triangulares jumbo ↗',
      de: 'Jumbo Buntstifte ansehen ↗',
      fr: 'Découvrir les crayons triangulaires ↗',
      it: 'Scopri le matite triangolari jumbo ↗',
      vi: 'Xem bút chì màu tam giác chống mỏi ↗',
    },
    coupangUrl:
      'https://www.coupang.com/np/search?component=&q=%EC%96%B4%EB%A6%B0%EC%9D%B4+%EC%82%BC%EA%B0%81+%EC%A0%90%EB%B3%B4+%EC%83%89%EC%97%B0%ED%95%84',
    amazonUrl: 'https://www.amazon.com/s?k=Jumbo+Triangular+Colored+Pencils+for+Kids',
  },
  {
    id: '03_markers',
    image: '/affiliate/affiliate_03_markers.webp',
    badge: {
      ko: "✨ DOOLIA'S PICK",
      en: "✨ DOOLIA'S PICK",
      ja: "✨ DOOLIA'S PICK",
      zh: '✨ DOOLIA 精選',
      es: '✨ SELECCIÓN DOOLIA',
      pt: '✨ ESCOLHA DOOLIA',
      de: '✨ DOOLIA EMPFEHLUNG',
      fr: '✨ SÉLECTION DOOLIA',
      it: '✨ SCELTO DA DOOLIA',
      vi: '✨ LỰA CHỌN DOOLIA',
    },
    headline: {
      ko: '뚜껑 열려도 오래 쓰는 안심 워셔블 수성 사인펜',
      en: 'Ultra-Washable Long-Lasting Kids Marker Pens',
      ja: 'フタを開けたままでも乾きにくい安心水性ペン',
      zh: '開蓋不易乾涸、水洗即淨的兒童水性彩色筆',
      es: 'Rotuladores lavables y duraderos para niños',
      pt: 'Canetinhas laváveis e duráveis para crianças',
      de: 'Abwaschbare und langlebige Filzstifte für Kinder',
      fr: 'Feutres lavables et durables pour enfants',
      it: 'Pennarelli lavabili e durevoli per bambini',
      vi: 'Bút lông màu gốc nước dễ tẩy rửa, lâu khô mực cho bé',
    },
    painPoint: {
      ko: '뚜껑을 안 닫아 금방 말라버린 사인펜이 많았나요?',
      en: 'Tired of dried-out markers with lost caps?',
      ja: 'キャップの閉め忘れですぐにインクが乾いて困っていませんか？',
      zh: '常常因為蓋子沒蓋好而乾掉整盒彩色筆嗎？',
      es: '¿Cansado de rotuladores secos porque se pierden las tapas?',
      pt: 'Cansado de canetinhas secas por ficarem destampadas?',
      de: 'Ärgern Sie sich über ausgetrocknete Stifte ohne Kappe?',
      fr: 'Marre des feutres qui sèchent sans leur bouchon ?',
      it: 'Stanco dei pennarelli che si seccano senza cappuccio?',
      vi: 'Bực mình vì bút lông bị khô mực do bé quên đậy nắp?',
    },
    benefit1: {
      ko: '피부와 옷에 묻어도 물로 쏙 지워지는 수성 잉크',
      en: 'Ultra-washable water-based ink cleans easily from skin and clothes',
      ja: '肌や服についても水洗いで簡単に落ちる水性インク',
      zh: '水性安全墨水，沾染皮膚或衣物清水即可洗淨',
      es: 'Tinta a base de agua lavable fácilmente de piel y ropa',
      pt: 'Tinta à base de água super lavável da pele e tecidos',
      de: 'Wasserbasierte Tinte lässt sich leicht von Haut und Textilien auswaschen',
      fr: 'Encre à base d’eau ultra-lavable sur la peau et le textile',
      it: 'Inchiostro a base d’acqua lavabile da pelle e tessuti',
      vi: 'Mực gốc nước dễ dàng giặt sạch khỏi da và vải',
    },
    benefit2: {
      ko: '아이가 꾹꾹 눌러 써도 밀려 들어가지 않는 튼튼한 닙',
      en: 'Durable pressure-resistant nib won’t push in under hard pressing',
      ja: '強い筆圧で押し込んでもペン先が潰れにくい高耐久設計',
      zh: '堅固抗壓筆頭，大力按壓也不易凹陷損壞',
      es: 'Punta resistente que no se hunde ante la presión fuerte',
      pt: 'Ponta durável e resistente que não afunda com a pressão',
      de: 'Robuste Spitze, die auch bei starkem Druck nicht eindrückt',
      fr: 'Pointe bloquée ultra-résistante à la pression des enfants',
      it: 'Punta resistente che non rientra nemmeno se premuta forte',
      vi: 'Đầu bút chắc chắn không bị thụt vào khi bé ấn mạnh',
    },
    ctaText: {
      ko: '물로 지워지는 키즈 수성 사인펜 둘러보기 ↗',
      en: 'View Washable Marker Pens ↗',
      ja: '水で落ちるキッズ水性ペンを見る ↗',
      zh: '查看可水洗兒童彩色筆 ↗',
      es: 'Ver rotuladores lavables ↗',
      pt: 'Ver canetinhas laváveis ↗',
      de: 'Abwaschbare Filzstifte ansehen ↗',
      fr: 'Découvrir les feutres lavables ↗',
      it: 'Scopri i pennarelli lavabili ↗',
      vi: 'Xem bút lông màu gốc nước dễ tẩy ↗',
    },
    coupangUrl:
      'https://www.coupang.com/np/search?component=&q=%EC%96%B4%EB%A6%B0%EC%9D%B4+%EC%9B%8C%EC%85%94%EB%B8%94+%EC%88%98%EC%84%B1+%EC%82%AC%EC%9D%B8%ED%8E%9C',
    amazonUrl: 'https://www.amazon.com/s?k=Washable+Markers+for+Kids',
  },
  {
    id: '04_water_brush',
    image: '/affiliate/affiliate_04_water_brush.webp',
    badge: {
      ko: "✨ DOOLIA'S PICK",
      en: "✨ DOOLIA'S PICK",
      ja: "✨ DOOLIA'S PICK",
      zh: '✨ DOOLIA 精選',
      es: '✨ SELECCIÓN DOOLIA',
      pt: '✨ ESCOLHA DOOLIA',
      de: '✨ DOOLIA EMPFEHLUNG',
      fr: '✨ SÉLECTION DOOLIA',
      it: '✨ SCELTO DA DOOLIA',
      vi: '✨ LỰA CHỌN DOOLIA',
    },
    headline: {
      ko: '물통 엎지를 걱정 없는 신개념 워터 브러쉬 펜',
      en: 'No-Spill Water Brush Pens for Mess-Free Watercolor',
      ja: '水入れ不要！こぼれる心配のないウォーターブラシペン',
      zh: '告別打翻水洗筆筒！免洗水彩自來水畫筆',
      es: 'Pinceles de agua antiderrames para pintar sin desastres',
      pt: 'Pincéis com reservatório de água sem sujeira nem derramamento',
      de: 'Auslaufsichere Wassertankpinsel für sauberen Malspaß',
      fr: 'Pinceaux à réservoir d’eau sans risque de renverser l’eau',
      it: 'Pennelli con serbatoio d’acqua a prova di schizzi',
      vi: 'Bút cọ tích hợp bình chứa nước thông minh không lo đổ nước',
    },
    painPoint: {
      ko: '물감 놀이할 때 물통이 쏟아질까 봐 조마조마하셨나요?',
      en: 'Constantly worried about tipped-over water cups while painting?',
      ja: '絵の具遊びの時、水入れを倒さないかヒヤヒヤしていませんか？',
      zh: '孩子畫水彩時，總擔心洗筆水桶被碰翻弄濕整桌嗎？',
      es: '¿Sufres pensando que el vaso de agua se derramará al pintar?',
      pt: 'Preocupado com copos de água virando durante a pintura?',
      de: 'Ständige Sorge vor umkippenden Wasserbechern beim Malen?',
      fr: 'Toujours peur que le gobelet d’eau ne se renverse sur la table ?',
      it: 'Ansia che il bicchiere d’acqua si rovesci durante la pittura?',
      vi: 'Bạn có sợ bé làm đổ cốc nước rửa cọ khi vẽ màu nước không?',
    },
    benefit1: {
      ko: '펜 몸통에 물을 채워 엎지를 걱정 없는 깔끔한 수채 놀이',
      en: 'Built-in refillable water reservoir eliminates messy water spills',
      ja: '軸に水を入れて使うため、水がこぼれずテーブルもすっきり',
      zh: '筆桿自帶儲水空間，完全不需額外水杯，告別桌面淹水',
      es: 'Depósito de agua integrado para pintar sin ensuciar la mesa',
      pt: 'Reservatório de água integrado que elimina bagunça e sujeira',
      de: 'Integrierter Wassertank verhindert verschüttetes Wasser am Tisch',
      fr: 'Réservoir d’eau intégré éliminant les risques de renversement',
      it: 'Serbatoio d’acqua ricaricabile integrato per dipingere in ordine',
      vi: 'Bình chứa nước ngay trên thân bút, không cần cốc nước rườm rà',
    },
    benefit2: {
      ko: '부드럽고 갈라짐 없는 탄력적인 고급 나일론 모',
      en: 'High-quality flexible nylon bristles that keep their shape',
      ja: 'まとまりが良く毛先が割れにくい高級ナイロン筆毛',
      zh: '柔軟彈性尼龍刷毛，不易分叉變形',
      es: 'Cerdas de nailon de alta calidad flexibles y duraderas',
      pt: 'Cerdas de nylon duráveis que mantêm a ponta perfeita',
      de: 'Hochwertige flexible Nylonborsten für saubere Pinselstriche',
      fr: 'Poils en nylon souples et durables qui gardent leur forme',
      it: 'Setole in nylon resistenti che non perdono la forma',
      vi: 'Lông cọ nylon đàn hồi cao cấp, không bị tưa hay rụng lông',
    },
    ctaText: {
      ko: '물 안 쏟는 워터 브러쉬 펜 세트 둘러보기 ↗',
      en: 'View Water Brush Pens ↗',
      ja: '水がこぼれない水筆ペンセットを見る ↗',
      zh: '查看免洗水彩儲水筆組 ↗',
      es: 'Ver pinceles con depósito de agua ↗',
      pt: 'Ver pincéis com reservatório ↗',
      de: 'Wassertankpinsel ansehen ↗',
      fr: 'Découvrir les pinceaux à eau ↗',
      it: 'Scopri i pennelli con serbatoio ↗',
      vi: 'Xem bộ bút cọ nước tiện lợi ↗',
    },
    coupangUrl:
      'https://www.coupang.com/np/search?component=&q=%EC%9B%8C%ED%84%B0+%EB%B8%8C%EB%9F%AC%EC%89%AC+%ED%8E%9C+%EC%84%B8%ED%8A%B8',
    amazonUrl: 'https://www.amazon.com/s?k=Water+Brush+Pens+for+Kids',
  },
  {
    id: '05_art_smock',
    image: '/affiliate/affiliate_05_art_smock.webp',
    badge: {
      ko: "✨ DOOLIA'S PICK",
      en: "✨ DOOLIA'S PICK",
      ja: "✨ DOOLIA'S PICK",
      zh: '✨ DOOLIA 精選',
      es: '✨ SELECCIÓN DOOLIA',
      pt: '✨ ESCOLHA DOOLIA',
      de: '✨ DOOLIA EMPFEHLUNG',
      fr: '✨ SÉLECTION DOOLIA',
      it: '✨ SCELTO DA DOOLIA',
      vi: '✨ LỰA CHỌN DOOLIA',
    },
    headline: {
      ko: '옷 버림 없이 마음껏 그리는 유아 방수 미술가운',
      en: 'Waterproof Long Sleeve Art Smock for Mess-Free Play',
      ja: '洋服を汚さず思い切り描けるキッズ防水お絵描きスモック',
      zh: '再也不怕弄髒衣服！兒童全包覆長袖防水畫畫圍裙',
      es: 'Mandil impermeable de manga larga para pintar sin manchas',
      pt: 'Avental impermeável de manga longa para pintura infantil',
      de: 'Wasserdichter Malkittel mit langen Ärmeln für Kinder',
      fr: 'Tablier de peinture imperméable à manches longues pour enfant',
      it: 'Grembiule impermeabile a maniche lunghe per piccoli artisti',
      vi: 'Áo yếm vẽ tranh chống thấm nước toàn thân cho bé thỏa sức sáng tạo',
    },
    painPoint: {
      ko: '아이가 아끼는 예쁜 옷에 물감이 묻을까 봐 걱정되셨나요?',
      en: 'Afraid of paint and marker stains ruining favorite clothes?',
      ja: 'お気に入りの洋服に絵の具がついて落ちなくなるのが心配ですか？',
      zh: '總擔心顏料弄髒孩子最喜歡的漂亮衣服嗎？',
      es: '¿Temes que la pintura arruine la ropa favorita de tu peque?',
      pt: 'Preocupado com manchas de tinta estragando as roupas do seu filho?',
      de: 'Angst, dass Farben die Lieblingskleidung ruinieren?',
      fr: 'Peur que la peinture n’abîme les beaux vêtements de votre enfant ?',
      it: 'Paura che i colori macchino i vestiti preferiti del tuo bimbo?',
      vi: 'Bạn sợ vết màu nước làm hỏng bộ quần áo đẹp của bé?',
    },
    benefit1: {
      ko: '소매 끝 밴딩과 전면 완벽 방수로 깔끔한 놀이 환경',
      en: 'Full waterproof coverage with snug elastic cuffs keeps clothes spotless',
      ja: '袖口のゴムと前面防水仕様でインクや水の浸透を完全ブロック',
      zh: '袖口鬆緊帶防漏設計與全正面防水面料，滴水不漏',
      es: 'Cobertura impermeable total con puños elásticos ajustados',
      pt: 'Proteção impermeável completa com punhos elásticos confortáveis',
      de: 'Vollständiger Nässeschutz mit bequemen elastischen Bündchen',
      fr: 'Protection imperméable intégrale avec poignets élastiqués',
      it: 'Protezione impermeabile completa con polsini elasticizzati',
      vi: 'Chống thấm nước tuyệt đối kết hợp bo chun cổ tay gọn gàng',
    },
    benefit2: {
      ko: '물티슈로 슥 닦거나 가볍게 물세탁 가능한 가벼운 원단',
      en: 'Lightweight breathable fabric that wipes clean in seconds',
      ja: 'ウェットティッシュで拭くだけ、丸洗いもできる軽量素材',
      zh: '輕薄透氣材質，濕紙巾一擦即淨，亦可輕鬆水洗',
      es: 'Tejido ligero y transpirable que se limpia con una toallita húmeda',
      pt: 'Tecido leve e respirável que limpa fácil com pano úmido',
      de: 'Leichter, atmungsaktiver Stoff, der sich leicht abwischen lässt',
      fr: 'Tissu léger et respirant nettoyable d’un simple coup d’éponge',
      it: 'Tessuto leggero e traspirante facile da pulire con un panno',
      vi: 'Chất liệu vải siêu nhẹ thoáng khí, lau sạch bằng khăn ướt trong tích tắc',
    },
    ctaText: {
      ko: '안심 방수 유아 미술가운 둘러보기 ↗',
      en: 'View Waterproof Art Smocks ↗',
      ja: '安心防水キッズスモックを見る ↗',
      zh: '查看長袖防水畫畫衣 ↗',
      es: 'Ver mandiles impermeables ↗',
      pt: 'Ver aventais impermeáveis ↗',
      de: 'Wasserdichte Malkittel ansehen ↗',
      fr: 'Découvrir les tabliers de peinture ↗',
      it: 'Scopri i grembiuli impermeabili ↗',
      vi: 'Xem áo yếm vẽ tranh chống thấm ↗',
    },
    coupangUrl:
      'https://www.coupang.com/np/search?component=&q=%EC%9C%A0%EC%95%84+%EB%B0%A9%EC%88%98+%EB%AF%B8%EC%88%A0%EA%B0%80%EC%9A%B4+%EC%A0%84%EC%8B%A0',
    amazonUrl: 'https://www.amazon.com/s?k=Waterproof+Kids+Art+Smock+Long+Sleeve',
  },
  {
    id: '06_craft_mat',
    image: '/affiliate/affiliate_06_craft_mat.webp',
    badge: {
      ko: "✨ DOOLIA'S PICK",
      en: "✨ DOOLIA'S PICK",
      ja: "✨ DOOLIA'S PICK",
      zh: '✨ DOOLIA 精選',
      es: '✨ SELECCIÓN DOOLIA',
      pt: '✨ ESCOLHA DOOLIA',
      de: '✨ DOOLIA EMPFEHLUNG',
      fr: '✨ SÉLECTION DOOLIA',
      it: '✨ SCELTO DA DOOLIA',
      vi: '✨ LỰA CHỌN DOOLIA',
    },
    headline: {
      ko: '테이블 오염 완벽 차단! 대형 실리콘 미술 매트',
      en: 'Extra Large Silicone Craft Mat with Cleaning Cup',
      ja: '机の汚れを完全ガード！大判シリコン製お絵描きマット',
      zh: '桌面髒污完全防護！多功能大尺寸矽膠畫畫墊',
      es: 'Tapete de silicona extra grande para manualidades infantiles',
      pt: 'Tapete de silicone grande para atividades artísticas infantis',
      de: 'Extra große Silikon-Bastelmatte für saubere Tische',
      fr: 'Grand tapis en silicone pour activités manuelles et peinture',
      it: 'Tappetino in silicone extra large per lavoretti e pittura',
      vi: 'Thảm vẽ tranh silicon cỡ lớn bảo vệ bàn học sạch sẽ',
    },
    painPoint: {
      ko: '식탁이나 책상에 낙서가 배어들까 봐 전전긍긍하셨나요?',
      en: 'Stressing over marker bleed-through and table scratches?',
      ja: 'テーブルにインクが染み込んだり傷がついたりするのが気になりますか？',
      zh: '害怕彩色筆穿透紙張染色在餐桌或書桌上嗎？',
      es: '¿Te agobia que los rotuladores traspasen y manchen la mesa?',
      pt: 'Preocupado com canetinhas manchando a mesa de casa?',
      de: 'Angst vor durchdrückenden Stiften und Kratzern auf dem Tisch?',
      fr: 'Inquiet des traces de feutre qui traversent sur la table ?',
      it: 'Preoccupato per i segni di pennarello che rovinano il tavolo?',
      vi: 'Lo lắng mực bút thấm qua giấy làm ố bẩn mặt bàn?',
    },
    benefit1: {
      ko: '물세척 한 번으로 끝나는 무독성 식품용 실리콘',
      en: '100% Food-grade non-stick silicone washes clean with water',
      ja: '水洗いですぐキレイになる安全な食品グレードシリコン素材',
      zh: '食品級無毒矽膠，水龍頭下一沖即淨不卡色',
      es: 'Silicona de grado alimentario 100% segura y lavable con agua',
      pt: 'Silicone de grau alimentício atóxico e super fácil de lavar',
      de: '100% lebensmittelechtes Silikon, schnell abwaschbar',
      fr: 'Silicone de qualité alimentaire 100% sûr, lavable à l’eau',
      it: 'Silicone alimentare sicuro, si lava in un attimo con acqua',
      vi: 'Chất liệu silicon thực phẩm an toàn, rửa sạch trôi màu chỉ với nước',
    },
    benefit2: {
      ko: '물감 팔레트와 붓 거치 공간이 빌트인된 깔끔한 편의성',
      en: 'Built-in paint wells and brush holders keep craft time tidy',
      ja: '絵の具パレットや筆置きが一体型になった便利なオールインワン設計',
      zh: '內建調色格與筆架凹槽，繪畫工具收納井然有序',
      es: 'Compartimentos integrados para pintura y soportes para pinceles',
      pt: 'Divisórias integradas para tintas e suporte para pincéis',
      de: 'Integrierte Farbvertiefungen und Pinselhalter für Ordnung',
      fr: 'Godets de peinture et porte-pinceaux intégrés très pratiques',
      it: 'Scomparti per colori e porta pennelli integrati salva-spazio',
      vi: 'Tích hợp khay pha màu và rãnh gác cọ tiện lợi, gọn gàng',
    },
    ctaText: {
      ko: '정리가 쉬운 대형 실리콘 미술 매트 둘러보기 ↗',
      en: 'View Silicone Craft Mats ↗',
      ja: '片付け簡単な大判シリコンマットを見る ↗',
      zh: '查看多功能矽膠畫墊 ↗',
      es: 'Ver tapetes de silicona para manualidades ↗',
      pt: 'Ver tapetes de silicone para artesanato ↗',
      de: 'Silikon-Bastelmatten ansehen ↗',
      fr: 'Découvrir les tapis en silicone ↗',
      it: 'Scopri i tappetini in silicone ↗',
      vi: 'Xem thảm silicon vẽ tranh cỡ lớn ↗',
    },
    coupangUrl:
      'https://www.coupang.com/np/search?component=&q=%EC%9C%A0%EC%95%84+%EC%8B%A4%EB%A6%AC%EC%BD%98+%EB%AF%B8%EC%88%A0+%EB%A7%A4%ED%8A%B8+%EB%8C%80%ED%98%95',
    amazonUrl: 'https://www.amazon.com/s?k=Silicone+Craft+Mat+for+Kids',
  },
  {
    id: '07_safety_scissors',
    image: '/affiliate/affiliate_07_safety_scissors.webp',
    badge: {
      ko: "✨ DOOLIA'S PICK",
      en: "✨ DOOLIA'S PICK",
      ja: "✨ DOOLIA'S PICK",
      zh: '✨ DOOLIA 精選',
      es: '✨ SELECCIÓN DOOLIA',
      pt: '✨ ESCOLHA DOOLIA',
      de: '✨ DOOLIA EMPFEHLUNG',
      fr: '✨ SÉLECTION DOOLIA',
      it: '✨ SCELTO DA DOOLIA',
      vi: '✨ LỰA CHỌN DOOLIA',
    },
    headline: {
      ko: '손 베일 걱정 없는 둥근 안전 가위',
      en: 'Safe Blunt-Tip Preschool Training Scissors',
      ja: '手を切る心配のない丸い刃先の子ども用安全はさみ',
      zh: '圓頭防夾手、專為幼兒設計的安全剪刀',
      es: 'Tijeras de seguridad con punta redonda para preescolar',
      pt: 'Tesouras infantis de segurança com ponta arredondada',
      de: 'Kindersichere Schere mit abgerundeter Spitze',
      fr: 'Ciseaux de sécurité à bouts ronds pour tout-petits',
      it: 'Forbici di sicurezza a punta arrotondata per bambini',
      vi: 'Kéo cắt giấy an toàn đầu bo tròn không lo đứt tay cho bé',
    },
    painPoint: {
      ko: '아이가 혼자 가위질할 때 다칠까 봐 손을 못 떼셨나요?',
      en: 'Afraid of accidental cuts when your toddler practices scissor skills?',
      ja: 'お子様のはさみ練習で手を切らないか不安ではありませんか？',
      zh: '孩子練習剪紙時，總是提心吊膽怕剪到手指嗎？',
      es: '¿Miedo a que tu hijo se corte al practicar con las tijeras?',
      pt: 'Medo de acidentes quando a criança usa tesoura sozinha?',
      de: 'Angst vor Schnittverletzungen bei den ersten Scherversuchen?',
      fr: 'Peur des coupures lorsque votre enfant apprend à découper ?',
      it: 'Ansia da tagli quando il bambino impara a usare le forbici?',
      vi: 'Bạn luôn lo bé cắt vào tay khi tập dùng kéo thủ công?',
    },
    benefit1: {
      ko: '종이만 잘리고 살이나 옷은 안 잘리는 안심 날 설계',
      en: 'Safety blades only cut paper, keeping skin, hair, and clothes safe',
      ja: '紙だけが切れて肌や髪は切れない安心の安全ブレード',
      zh: '特殊安全刀刃，只剪紙張不傷肌膚與衣物',
      es: 'Cuchillas seguras que solo cortan papel, no la piel ni la ropa',
      pt: 'Lâminas que cortam apenas papel, sem risco para pele ou roupas',
      de: 'Sicherheitsklingen schneiden nur Papier, keine Haut oder Haare',
      fr: 'Lames sécurisées coupant uniquement le papier, sans danger pour la peau',
      it: 'Lame di sicurezza che tagliano solo la carta, non la pelle',
      vi: 'Lưỡi kéo an toàn chỉ cắt được giấy, không làm đứt da hay quần áo',
    },
    benefit2: {
      ko: '손 힘이 약한 유아도 쉽게 오릴 수 있는 스프링 지지대',
      en: 'Spring-assisted lever automatically reopens for effortless cutting',
      ja: '弱い握力でもスイスイ切れるスプリングアシスト機能',
      zh: '省力彈簧輔助把手，手部小肌肉輕鬆開合剪裁',
      es: 'Palanca con resorte que ayuda a abrir la tijera sin esfuerzo',
      pt: 'Mola auxiliar que reabre a tesoura facilitando o corte',
      de: 'Federunterstützung erleichtert das Schneiden für kleine Hände',
      fr: 'Ressort d’ouverture automatique facilitant la découpe',
      it: 'Leva a molla che aiuta la riapertura automatica della forbice',
      vi: 'Lò xo trợ lực tự động mở miệng kéo giúp bé cắt không tốn sức',
    },
    ctaText: {
      ko: '다칠 걱정 없는 어린이 안전가위 둘러보기 ↗',
      en: 'View Safe Toddler Scissors ↗',
      ja: '安心の子ども用安全はさみを見る ↗',
      zh: '查看幼兒安全剪刀 ↗',
      es: 'Ver tijeras de seguridad para niños ↗',
      pt: 'Ver tesouras de segurança infantil ↗',
      de: 'Kindersichere Scheren ansehen ↗',
      fr: 'Découvrir les ciseaux de sécurité ↗',
      it: 'Scopri le forbici di sicurezza ↗',
      vi: 'Xem kéo an toàn cho trẻ em ↗',
    },
    coupangUrl:
      'https://www.coupang.com/np/search?component=&q=%EC%96%B4%EB%A6%B0%EC%9D%B4+%EC%95%88%EC%A0%84%EA%B0%80%EC%9C%84+%EC%9C%A0%EC%95%84',
    amazonUrl: 'https://www.amazon.com/s?k=Toddler+Safety+Scissors+for+Kids',
  },
  {
    id: '08_kids_art_set',
    image: '/affiliate/affiliate_08_kids_art_set.webp',
    badge: {
      ko: "✨ DOOLIA'S PICK",
      en: "✨ DOOLIA'S PICK",
      ja: "✨ DOOLIA'S PICK",
      zh: '✨ DOOLIA 精選',
      es: '✨ SELECCIÓN DOOLIA',
      pt: '✨ ESCOLHA DOOLIA',
      de: '✨ DOOLIA EMPFEHLUNG',
      fr: '✨ SÉLECTION DOOLIA',
      it: '✨ SCELTO DA DOOLIA',
      vi: '✨ LỰA CHỌN DOOLIA',
    },
    headline: {
      ko: '하나로 끝내는 올인원 어린이 종합 미술세트',
      en: 'All-In-One Deluxe Kids Art Supplies Gift Set',
      ja: 'これ一つでOK！オールインワン子ども用お絵描き総合セット',
      zh: '一盒搞定所有美術用具！兒童豪華全方位畫具手提禮盒',
      es: 'Set completo de arte para niños con estuche portátil',
      pt: 'Kit completo de pintura e arte infantil em maleta',
      de: 'All-in-One Malset im praktischen Koffer für Kinder',
      fr: 'Coffret d’art complet pour enfant avec mallette de transport',
      it: 'Set artistico completo per bambini in pratica valigetta',
      vi: 'Hộp bút vẽ nghệ thuật đa năng cao cấp cho bé',
    },
    painPoint: {
      ko: '미술도구를 따로 사기 번거롭고 정리가 잘 안 되나요?',
      en: 'Tired of buying separate supplies and dealing with messy clutter?',
      ja: '画材を別々に買うのが面倒で、お片付けも大変ではありませんか？',
      zh: '各種畫筆分開買又貴又麻煩，收拾起來總是亂糟糟嗎？',
      es: '¿Cansado de comprar materiales sueltos y del desorden en casa?',
      pt: 'Cansado de comprar materiais separados e da bagunça de lápis espalhados?',
      de: 'Genervt vom Nachkaufen einzelner Stifte und dem Chaos im Zimmer?',
      fr: 'Fatigué d’acheter les fournitures séparément et du désordre ?',
      it: 'Stanco di comprare accessori sparsi e del disordine in casa?',
      vi: 'Mệt mỏi vì phải mua lẻ từng món và phòng luôn bừa bộn sau khi vẽ?',
    },
    benefit1: {
      ko: '색연필·사인펜·크레파스 등 풍성한 도구가 한 번에',
      en: 'Complete variety including crayons, colored pencils, and markers',
      ja: '色鉛筆、マーカー、クレヨンなど豊富な画材が一つにぎっしり',
      zh: '彩色筆、色鉛筆、蠟筆等超齊全用具，應有盡有',
      es: 'Gran variedad con crayones, lápices de colores y rotuladores',
      pt: 'Variedade completa com gizes, lápis de cor e canetinhas',
      de: 'Riesige Auswahl an Buntstiften, Wachsmalern und Filzstiften',
      fr: 'Large variété d’outils : craies, crayons de couleur et feutres',
      it: 'Grande varietà con pastelli, matite colorate e pennarelli',
      vi: 'Đầy đủ sáp màu, bút lông, bút chì màu và phụ kiện vẽ',
    },
    benefit2: {
      ko: '손잡이 가방형 케이스로 스스로 정리하는 습관 형성',
      en: 'Portable carry case encourages self-cleanup and easy travel',
      ja: '取っ手付きケースでどこでも持ち運べて、お片付け習慣も身につく',
      zh: '手提便攜外盒，好收納好攜帶，培養孩子物歸原位的好習慣',
      es: 'Estuche portátil con asa que enseña a ordenar y fácil de llevar',
      pt: 'Maleta prática com alça que estimula a organização autônoma',
      de: 'Tragbarer Koffer fördert spielerisch das Aufräumen nach dem Malen',
      fr: 'Mallette avec poignée facilitant le rangement et le transport',
      it: 'Valigetta portatile che insegna l’ordine e comoda da portare in giro',
      vi: 'Hộp vali có quai xách tiện lợi giúp bé rèn luyện tính ngăn nắp',
    },
    ctaText: {
      ko: '선물하기 좋은 종합 미술세트 둘러보기 ↗',
      en: 'View Deluxe Kids Art Sets ↗',
      ja: 'プレゼントにも最適な総合アートセットを見る ↗',
      zh: '查看兒童豪華美術禮盒 ↗',
      es: 'Ver sets de arte para niños ↗',
      pt: 'Ver kits de arte infantil ↗',
      de: 'Malsets für Kinder ansehen ↗',
      fr: 'Découvrir les coffrets d’art ↗',
      it: 'Scopri i set artistici per bambini ↗',
      vi: 'Xem bộ hộp quà dụng cụ vẽ cao cấp ↗',
    },
    coupangUrl:
      'https://www.coupang.com/np/search?component=&q=%EC%96%B4%EB%A6%B0%EC%9D%B4+%EC%A2%85%ED%95%A9+%EB%AF%B8%EC%88%A0%EC%84%B8%ED%8A%B8+%EC%BC%80%EC%9D%B4%EC%8A%A4',
    amazonUrl: 'https://www.amazon.com/s?k=Kids+Art+Set+with+Case',
  },
]

const SUPPORTED_LANGS: SupportedLang[] = ['ko', 'en', 'ja', 'zh', 'es', 'pt', 'de', 'fr', 'it', 'vi']

let currentAffiliateIndex = Math.floor(Math.random() * AFFILIATE_ITEMS.length)

export function getNextAffiliateItem(): AffiliateItem {
  const item = AFFILIATE_ITEMS[currentAffiliateIndex]
  currentAffiliateIndex = (currentAffiliateIndex + 1) % AFFILIATE_ITEMS.length
  return item
}

export function pickAffiliateText(text: LocalizedText, lang: string): string {
  const code = (lang.split('-')[0] || 'en') as SupportedLang
  if (SUPPORTED_LANGS.includes(code)) return text[code]
  return text.en || text.ko
}

export function getAffiliateLink(item: AffiliateItem, lang: string): string {
  return (lang.split('-')[0] || 'en') === 'ko' ? item.coupangUrl : item.amazonUrl
}
