import { SITUATION_ITEMS, type SituationId } from '@/shared/config/playSituations'

export interface PlaySolution {
  id: string
  situation: SituationId
  situationLabel: string
  title: string
  desc: string
  time: string
  age: string
  material: string
  suppliesDetail: string
  imageUrl: string
  badgeColor: string
  printQuery: string
  steps: [string, string, string]
}

export const PLAY_SOLUTIONS: PlaySolution[] = [
  {
    id: 'sol-1',
    situation: 'home',
    situationLabel: '🏠 집에서 놀기',
    title: '택배 상자 미니 슈퍼카 대시보드',
    desc: '버리는 상자 안쪽에 계기판 도안을 붙여 1시간 동안 신나는 거실 드라이브를 즐겨요.',
    time: '15분',
    age: '만 3~6세',
    material: '0원 상자',
    suppliesDetail: '도안 1장 + 빈 택배 상자 + 테이프',
    imageUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    printQuery: '자동차|탈것|계기판|차|트럭',
    steps: [
      '둘리아 계기판 도안을 A4로 바로 인쇄해요.',
      '현관에 두던 택배 상자 안쪽에 도안을 테이프로 붙여요.',
      '아이가 상자 안에 들어가 거실 드라이브를 즐기게 해주세요.',
    ],
  },
  {
    id: 'sol-2',
    situation: 'bedtime',
    situationLabel: '🌙 잠자리 전',
    title: '불 끄고 천장에 쏘는 손전등 우주선',
    desc: '도안 별자리에 구멍을 뚫고 손전등을 비추면 우리 집 침실이 환상적인 천문대로 변신해요.',
    time: '15분',
    age: '만 3~7세',
    material: '손전등',
    suppliesDetail: '도안 1장 + 연필/이쑤시개 + 스마트폰 손전등',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    printQuery: '우주|별|로켓|우주선',
    steps: [
      '별자리·우주 도안을 인쇄하고 점에 연필로 구멍을 콕콕 뚫어요.',
      '방 불을 끄고 스마트폰 손전등을 종이 뒤에 대어요.',
      '천장에 뜬 은하수를 보며 하루를 천천히 마무리해요.',
    ],
  },
  {
    id: 'sol-3',
    situation: 'home',
    situationLabel: '🏠 집에서 놀기',
    title: '아빠 등 위에서 달리는 롤러코스터 도로',
    desc: '부모는 엎드려 편히 쉬고, 아이는 등 위에 도안을 붙여 미니카를 굴리는 시원한 마사지 놀이!',
    time: '20분',
    age: '전 연령',
    material: '부모 쉼',
    suppliesDetail: '도안 1장 + 집에 있는 미니카 1~2대',
    imageUrl: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-rose-100 text-rose-800 border-rose-200',
    printQuery: '도로|미로|자동차|탈것',
    steps: [
      '도로·자동차 도안을 한 장 인쇄해요.',
      '소파나 침대에 엎드리고, 등 위에 도안을 올려요.',
      '아이가 미니카를 굴리며 시원한 등 마사지를 해줍니다.',
    ],
  },
  {
    id: 'sol-4',
    situation: 'quick',
    situationLabel: '⏱️ 10분 놀이',
    title: '굵은선 냠냠 과일 바구니 채우기',
    desc: '삐져나가지 않는 도톰한 테두리로 10분 만에 아이 혼자 완성하는 손가락 집중 놀이예요.',
    time: '10분',
    age: '만 2~4세',
    material: '준비 0초',
    suppliesDetail: '도안 1장 + 색연필 또는 크레파스',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    printQuery: '색칠|과일|굵은선|coloring',
    steps: [
      '굵은선 색칠 도안을 인쇄해요.',
      '크레파스만 꺼내 테두리 안을 천천히 채워요.',
      '10분 안에 끝낸 그림을 냉장고에 붙여 성취감을 남겨요.',
    ],
  },
  {
    id: 'sol-5',
    situation: 'outdoor',
    situationLabel: '🚗 외출할 때',
    title: '초미세 정글 숲 숨은그림찾기',
    desc: '식당에서 음식 나오는 15분 동안 유튜브 영상 대신 아이의 눈을 사로잡는 관찰력 도안!',
    time: '15분',
    age: '만 4~7세',
    material: '포터블',
    suppliesDetail: '도안 1장 + 형광펜 또는 연필',
    imageUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-sky-100 text-sky-800 border-sky-200',
    printQuery: '숨은그림|관찰|정글|동물|틀린그림',
    steps: [
      '외출 전에 숨은그림 도안을 한 장 접어 가방에 넣어요.',
      '식당에 앉으면 스마트폰 대신 도안과 형광펜을 꺼내요.',
      '음식이 나올 때까지 숨은 동물을 찾아 표시해요.',
    ],
  },
  {
    id: 'sol-6',
    situation: 'home',
    situationLabel: '🏠 집에서 놀기',
    title: '휴지심 2개 우주 은하수 망원경',
    desc: '다 쓴 휴지심 2개를 연결해 거실 구석구석을 비밀 탐험하는 0원 재활용 놀이 레시피예요.',
    time: '20분',
    age: '만 3~6세',
    material: '휴지심',
    suppliesDetail: '도안 1장 + 다 쓴 휴지심 2개 + 테이프',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    printQuery: '우주|로켓|오리기|만들기|cutout',
    steps: [
      '우주·오리기 도안을 인쇄해 휴지심에 둘러 붙여요.',
      '휴지심 2개를 이어 붙여 망원경 길이를 만들어요.',
      '집안 구석구석을 비밀 행성처럼 탐사해요.',
    ],
  },
  {
    id: 'sol-7',
    situation: 'special',
    situationLabel: '🎉 특별한 날',
    title: 'A4 1장 정글 대모험 주사위 보드게임',
    desc: '엉덩이 춤추기, 하이파이브 미션이 담겨 온 가족이 낄낄거리며 즐기는 주말 보드게임 대결!',
    time: '30분',
    age: '전 연령',
    material: '온가족',
    suppliesDetail: '도안 1장 + 동전/지우개 말 + 주사위',
    imageUrl: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-purple-100 text-purple-800 border-purple-200',
    printQuery: '보드게임|가족|게임|주사위',
    steps: [
      '보드게임 도안을 인쇄하고 지우개·동전을 말로 써요.',
      '주사위 대신 가위바위보나 동전 앞뒤로 칸을 이동해요.',
      '칸마다 적힌 가족 미션을 하며 결승선까지 달려요.',
    ],
  },
  {
    id: 'sol-8',
    situation: 'quick',
    situationLabel: '⏱️ 10분 놀이',
    title: '거실 탈출 비밀 스파이 암호 해독',
    desc: '숫자와 기호를 대조해 숨겨진 보물 단어를 찾아내는 10분 두뇌 풀가동 집중 미션지예요.',
    time: '10분',
    age: '만 5~7세',
    material: '자율집중',
    suppliesDetail: '도안 1장 + 연필 1자루',
    imageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    printQuery: '암호|미로|숫자|알파벳|퍼즐',
    steps: [
      '암호·미로 도안을 A4로 바로 인쇄해요.',
      '아이와 함께 힌트를 읽으며 빈칸을 채워요.',
      '10분 안에 해독한 답을 소리 내어 읽어 성취감을 남겨요.',
    ],
  },
  {
    id: 'sol-9',
    situation: 'outdoor',
    situationLabel: '🚗 외출할 때',
    title: '차창 밖 관찰 빙고',
    desc: '차 안·식당에서 보이는 것들을 칸마다 찾아 표시하는 대기 시간 꿀템이에요.',
    time: '15분',
    age: '만 3~7세',
    material: '포터블',
    suppliesDetail: '도안 1장 + 색연필',
    imageUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-sky-100 text-sky-800 border-sky-200',
    printQuery: '빙고|관찰|숨은그림|동물|찾기',
    steps: [
      '외출 전에 관찰 빙고 도안을 접어 가방에 넣어요.',
      '차 창밖이나 식당에서 보이는 것을 칸마다 찾아 표시해요.',
      '한 줄이 완성되면 작은 하이파이브로 대기 시간을 끝내요.',
    ],
  },
  {
    id: 'sol-10',
    situation: 'bedtime',
    situationLabel: '🌙 잠자리 전',
    title: '침실 벽에 띄우는 그림자 극장',
    desc: '불을 낮추고 손전등과 도안으로 벽에 그림자를 만들어 잠자리 분위기를 바꿔요.',
    time: '10분',
    age: '만 2~6세',
    material: '손전등',
    suppliesDetail: '도안 1장 + 손전등',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    printQuery: '그림자|실루엣|동물|오리기|cutout',
    steps: [
      '그림자·실루엣 도안을 인쇄해 가볍게 오려요.',
      '불을 낮추고 손전등을 도안 뒤에 대어요.',
      '벽에 뜬 그림자를 보며 짧은 이야기를 만들고 잠자리에 들어요.',
    ],
  },
  {
    id: 'sol-11',
    situation: 'special',
    situationLabel: '🎉 특별한 날',
    title: '한 장으로 완성하는 생일 파티 가랜드',
    desc: '오려 이어 붙이면 거실이 바로 파티장으로 바뀌는 기념일 레시피예요.',
    time: '20분',
    age: '만 3~7세',
    material: '파티',
    suppliesDetail: '도안 1장 + 가위 + 실/테이프',
    imageUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-violet-100 text-violet-800 border-violet-200',
    printQuery: '생일|파티|가랜드|시즌|기념일',
    steps: [
      '생일·시즌 가랜드 도안을 인쇄해요.',
      '아이와 함께 오려 실이나 테이프로 이어 붙여요.',
      '창가나 식탁 위에 걸어 특별한 날을 완성해요.',
    ],
  },
  {
    id: 'sol-12',
    situation: 'home',
    situationLabel: '🏠 집에서 놀기',
    title: '종이컵 로봇 변신 공작',
    desc: '종이컵에 도안을 붙여 거실 로봇 부대를 만들어요.',
    time: '15분',
    age: '만 3~6세',
    material: '0원 컵',
    suppliesDetail: '도안 1장 + 종이컵 + 테이프',
    imageUrl: 'https://images.unsplash.com/photo-1515488044360-fb630819f3ba?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    printQuery: '로봇|오리기|만들기|cutout',
    steps: ['로봇 도안을 인쇄해요.', '종이컵에 둘러 붙여요.', '거실을 탐험하는 로봇 놀이를 해요.'],
  },
  {
    id: 'sol-13',
    situation: 'home',
    situationLabel: '🏠 집에서 놀기',
    title: '소파 밑 보물 지도',
    desc: '거실을 탐험 무대로 바꾸는 한 장 보물찾기 지도예요.',
    time: '20분',
    age: '만 4~7세',
    material: '0원 지도',
    suppliesDetail: '도안 1장 + 연필',
    imageUrl: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    printQuery: '지도|미로|보물|탐험',
    steps: ['보물 지도 도안을 인쇄해요.', '거실 소품에 맞춰 X 표시를 해요.', '아이와 함께 보물을 찾아요.'],
  },
  {
    id: 'sol-14',
    situation: 'home',
    situationLabel: '🏠 집에서 놀기',
    title: '신문지 칼라 왕관 만들기',
    desc: '오려 붙이면 바로 왕국이 열리는 0원 역할극 소품이에요.',
    time: '15분',
    age: '만 3~6세',
    material: '신문지',
    suppliesDetail: '도안 1장 + 신문지 + 테이프',
    imageUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    printQuery: '왕관|오리기|공주|역할극',
    steps: ['왕관 도안을 인쇄해요.', '신문지에 붙여 잘라요.', '역할극으로 하루를 즐겨요.'],
  },
  {
    id: 'sol-15',
    situation: 'home',
    situationLabel: '🏠 집에서 놀기',
    title: '상자 속 비밀 성 만들기',
    desc: '택배 상자 하나를 성으로 바꾸는 집콕 공작이에요.',
    time: '20분',
    age: '만 3~7세',
    material: '0원 상자',
    suppliesDetail: '도안 1장 + 상자 + 테이프',
    imageUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    printQuery: '성|오리기|만들기|cutout',
    steps: ['성 도안을 인쇄해요.', '상자 안쪽에 붙여요.', '인형을 넣어 성 놀이를 해요.'],
  },
  {
    id: 'sol-16',
    situation: 'home',
    situationLabel: '🏠 집에서 놀기',
    title: '거실 캠핑 텐트 지도',
    desc: '이불 텐트 안에 지도를 펼치고 캠핑 탐험을 시작해요.',
    time: '15분',
    age: '만 2~5세',
    material: '이불',
    suppliesDetail: '도안 1장 + 이불',
    imageUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    printQuery: '캠핑|지도|동물|탐험',
    steps: ['캠핑 지도 도안을 인쇄해요.', '이불 텐트 안에 펼쳐요.', '손전등으로 탐험해요.'],
  },
  {
    id: 'sol-17',
    situation: 'quick',
    situationLabel: '⏱️ 10분 놀이',
    title: '1분 미로 탈출',
    desc: '한 장으로 끝나는 초간단 미로 집중 놀이예요.',
    time: '10분',
    age: '만 4~7세',
    material: '준비 0초',
    suppliesDetail: '도안 1장 + 연필',
    imageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    printQuery: '미로|집중|퍼즐',
    steps: ['미로 도안을 인쇄해요.', '연필로 길을 찾아요.', '성공하면 하이파이브해요.'],
  },
  {
    id: 'sol-18',
    situation: 'quick',
    situationLabel: '⏱️ 10분 놀이',
    title: '점잇기 로켓 발사',
    desc: '숫자 순서대로 이으면 로켓이 완성되는 10분 놀이예요.',
    time: '10분',
    age: '만 4~6세',
    material: '준비 0초',
    suppliesDetail: '도안 1장 + 연필',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    printQuery: '점잇기|숫자|로켓|우주',
    steps: ['점잇기 도안을 인쇄해요.', '숫자 순서대로 이어요.', '완성된 로켓을 색칠해요.'],
  },
  {
    id: 'sol-19',
    situation: 'quick',
    situationLabel: '⏱️ 10분 놀이',
    title: '다른그림 찾기 한 장',
    desc: '짧은 대기 시간에 눈을 깨우는 관찰력 미션지예요.',
    time: '10분',
    age: '만 4~7세',
    material: '준비 0초',
    suppliesDetail: '도안 1장 + 형광펜',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    printQuery: '다른그림|틀린그림|관찰',
    steps: ['다른그림 도안을 인쇄해요.', '다른 점을 동그라미해요.', '다 찾으면 자랑해요.'],
  },
  {
    id: 'sol-20',
    situation: 'quick',
    situationLabel: '⏱️ 10분 놀이',
    title: '숫자 따라쓰기 스피드',
    desc: '굵은선 숫자로 10분 만에 끝내는 손놀림 연습이에요.',
    time: '10분',
    age: '만 3~5세',
    material: '준비 0초',
    suppliesDetail: '도안 1장 + 색연필',
    imageUrl: 'https://images.unsplash.com/photo-1515488044360-fb630819f3ba?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    printQuery: '숫자|따라쓰기|알파벳',
    steps: ['숫자 도안을 인쇄해요.', '굵은선을 따라 써요.', '냉장고에 붙여 자랑해요.'],
  },
  {
    id: 'sol-21',
    situation: 'quick',
    situationLabel: '⏱️ 10분 놀이',
    title: '도형 냠냠 색칠',
    desc: '동그라미·세모를 채워 끝내는 초간단 색칠 놀이예요.',
    time: '10분',
    age: '만 2~4세',
    material: '준비 0초',
    suppliesDetail: '도안 1장 + 크레파스',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    printQuery: '색칠|도형|굵은선|coloring',
    steps: ['도형 색칠 도안을 인쇄해요.', '테두리 안만 채워요.', '10분 컷으로 마무리해요.'],
  },
  {
    id: 'sol-22',
    situation: 'quick',
    situationLabel: '⏱️ 10분 놀이',
    title: '알파벳 스탬프 찾기',
    desc: '숨은 알파벳을 찾아 동그라미 하는 초집중 미션이에요.',
    time: '10분',
    age: '만 5~7세',
    material: '자율집중',
    suppliesDetail: '도안 1장 + 연필',
    imageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    printQuery: '알파벳|찾기|퍼즐|암호',
    steps: ['알파벳 찾기 도안을 인쇄해요.', '목표 글자를 찾아요.', '다 찾으면 읽어 줘요.'],
  },
  {
    id: 'sol-23',
    situation: 'outdoor',
    situationLabel: '🚗 외출할 때',
    title: '식당 메뉴 관찰 빙고',
    desc: '음식이 나올 때까지 메뉴판을 관찰하는 대기 놀이예요.',
    time: '15분',
    age: '만 3~7세',
    material: '포터블',
    suppliesDetail: '도안 1장 + 펜',
    imageUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-sky-100 text-sky-800 border-sky-200',
    printQuery: '빙고|관찰|음식|찾기',
    steps: ['메뉴 빙고 도안을 접어 가요.', '보이는 것을 칸에 표시해요.', '한 줄이 되면 하이파이브해요.'],
  },
  {
    id: 'sol-24',
    situation: 'outdoor',
    situationLabel: '🚗 외출할 때',
    title: '대기줄 미로 한 장',
    desc: '병원·카페 대기줄에서 꺼내 쓰는 포켓 미로예요.',
    time: '10분',
    age: '만 4~7세',
    material: '포터블',
    suppliesDetail: '도안 1장 + 연필',
    imageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-sky-100 text-sky-800 border-sky-200',
    printQuery: '미로|집중|퍼즐',
    steps: ['미로 도안을 가방에 넣어요.', '대기 중에 길을 찾아요.', '끝나면 다음 장으로 넘어가요.'],
  },
  {
    id: 'sol-25',
    situation: 'outdoor',
    situationLabel: '🚗 외출할 때',
    title: '카페 숨은그림 한 장',
    desc: '창가 자리에서 조용히 끝내는 관찰력 도안이에요.',
    time: '15분',
    age: '만 4~7세',
    material: '포터블',
    suppliesDetail: '도안 1장 + 형광펜',
    imageUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-sky-100 text-sky-800 border-sky-200',
    printQuery: '숨은그림|관찰|동물|찾기',
    steps: ['숨은그림 도안을 꺼내요.', '숨은 동물을 찾아 표시해요.', '음료가 나올 때까지 이어가요.'],
  },
  {
    id: 'sol-26',
    situation: 'outdoor',
    situationLabel: '🚗 외출할 때',
    title: '차안 동물 찾기',
    desc: '창밖으로 지나가는 것들을 찾아 표시하는 드라이브 놀이예요.',
    time: '15분',
    age: '만 3~6세',
    material: '포터블',
    suppliesDetail: '도안 1장 + 색연필',
    imageUrl: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-sky-100 text-sky-800 border-sky-200',
    printQuery: '동물|찾기|관찰|빙고',
    steps: ['동물 찾기 도안을 펼쳐요.', '창밖 풍경과 맞춰 표시해요.', '목적지에 도착할 때까지 이어가요.'],
  },
  {
    id: 'sol-27',
    situation: 'outdoor',
    situationLabel: '🚗 외출할 때',
    title: '포켓 색칠 한 장',
    desc: '접어 가방에 넣는 굵은선 색칠 대기 꿀템이에요.',
    time: '10분',
    age: '만 2~4세',
    material: '포터블',
    suppliesDetail: '도안 1장 + 크레파스',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-sky-100 text-sky-800 border-sky-200',
    printQuery: '색칠|굵은선|coloring',
    steps: ['색칠 도안을 접어 가요.', '대기 중에 테두리를 채워요.', '끝나면 가방에 다시 넣어요.'],
  },
  {
    id: 'sol-28',
    situation: 'outdoor',
    situationLabel: '🚗 외출할 때',
    title: '틀린그림 포켓 미션',
    desc: '식당 테이블에서 바로 펼치는 한 장 관찰 미션이에요.',
    time: '15분',
    age: '만 4~7세',
    material: '포터블',
    suppliesDetail: '도안 1장 + 펜',
    imageUrl: 'https://images.unsplash.com/photo-1515488044360-fb630819f3ba?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-sky-100 text-sky-800 border-sky-200',
    printQuery: '틀린그림|다른그림|관찰',
    steps: ['틀린그림 도안을 꺼내요.', '다른 점을 찾아 표시해요.', '음식이 나오면 접어 둬요.'],
  },
  {
    id: 'sol-29',
    situation: 'bedtime',
    situationLabel: '🌙 잠자리 전',
    title: '별자리 찾기 밤하늘',
    desc: '불을 낮추고 별자리를 찾아 하루를 마무리해요.',
    time: '10분',
    age: '만 3~7세',
    material: '손전등',
    suppliesDetail: '도안 1장 + 손전등',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    printQuery: '별|우주|별자리|찾기',
    steps: ['별자리 도안을 인쇄해요.', '불을 낮추고 별을 찾아요.', '짧은 이야기로 잠자리에 들어요.'],
  },
  {
    id: 'sol-30',
    situation: 'bedtime',
    situationLabel: '🌙 잠자리 전',
    title: '달빛 색칠 한 장',
    desc: '조용히 달을 색칠하며 호흡을 고르는 밤 놀이예요.',
    time: '10분',
    age: '만 2~5세',
    material: '준비 0초',
    suppliesDetail: '도안 1장 + 색연필',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    printQuery: '달|색칠|우주|coloring',
    steps: ['달 색칠 도안을 인쇄해요.', '작은 소리로 색을 칠해요.', '불을 끄고 잠자리에 들어요.'],
  },
  {
    id: 'sol-31',
    situation: 'bedtime',
    situationLabel: '🌙 잠자리 전',
    title: '고요한 미로 산책',
    desc: '잠들기 전 천천히 길을 찾는 조용한 미로예요.',
    time: '10분',
    age: '만 4~7세',
    material: '준비 0초',
    suppliesDetail: '도안 1장 + 연필',
    imageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    printQuery: '미로|집중|퍼즐',
    steps: ['미로 도안을 침대 옆에 둬요.', '천천히 길을 찾아요.', '끝나면 불을 꺼요.'],
  },
  {
    id: 'sol-32',
    situation: 'bedtime',
    situationLabel: '🌙 잠자리 전',
    title: '양 세기 점잇기',
    desc: '점을 잇다 보면 양이 나타나 잠이 오는 레시피예요.',
    time: '10분',
    age: '만 3~6세',
    material: '준비 0초',
    suppliesDetail: '도안 1장 + 연필',
    imageUrl: 'https://images.unsplash.com/photo-1515488044360-fb630819f3ba?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    printQuery: '점잇기|숫자|동물',
    steps: ['점잇기 도안을 인쇄해요.', '숫자를 따라 이어요.', '양을 세며 잠자리에 들어요.'],
  },
  {
    id: 'sol-33',
    situation: 'bedtime',
    situationLabel: '🌙 잠자리 전',
    title: '손전등 동물원',
    desc: '벽에 동물 그림자를 띄워 짧은 동화를 만들어요.',
    time: '10분',
    age: '만 2~6세',
    material: '손전등',
    suppliesDetail: '도안 1장 + 손전등',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    printQuery: '그림자|동물|오리기|cutout',
    steps: ['동물 실루엣 도안을 오려요.', '손전등을 비춰요.', '짧은 이야기로 하루를 닫아요.'],
  },
  {
    id: 'sol-34',
    situation: 'bedtime',
    situationLabel: '🌙 잠자리 전',
    title: '꿈나라 가랜드 한 장',
    desc: '침대 헤드에 작게 걸어 두는 밤 감성 가랜드예요.',
    time: '15분',
    age: '만 3~7세',
    material: '손전등',
    suppliesDetail: '도안 1장 + 테이프',
    imageUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    printQuery: '가랜드|별|우주|시즌',
    steps: ['별 가랜드 도안을 인쇄해요.', '작게 오려 붙여요.', '침대 옆에 걸어 불을 꺼요.'],
  },
  {
    id: 'sol-35',
    situation: 'special',
    situationLabel: '🎉 특별한 날',
    title: '할로윈 마스크 한 장',
    desc: '오려 쓰면 바로 변신하는 기념일 마스크예요.',
    time: '20분',
    age: '만 3~7세',
    material: '파티',
    suppliesDetail: '도안 1장 + 가위 + 끈',
    imageUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-violet-100 text-violet-800 border-violet-200',
    printQuery: '할로윈|마스크|시즌|기념일',
    steps: ['마스크 도안을 인쇄해요.', '눈 부분을 오려요.', '파티 놀이에 써요.'],
  },
  {
    id: 'sol-36',
    situation: 'special',
    situationLabel: '🎉 특별한 날',
    title: '크리스마스 트리 장식',
    desc: '한 장으로 트리를 꾸미는 시즌 오리고 붙이기예요.',
    time: '20분',
    age: '만 3~7세',
    material: '파티',
    suppliesDetail: '도안 1장 + 가위 + 테이프',
    imageUrl: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-violet-100 text-violet-800 border-violet-200',
    printQuery: '크리스마스|트리|시즌|기념일',
    steps: ['트리 장식 도안을 인쇄해요.', '오려 창문에 붙여요.', '가족 사진을 찍어요.'],
  },
  {
    id: 'sol-37',
    situation: 'special',
    situationLabel: '🎉 특별한 날',
    title: '가족 미션 빙고',
    desc: '주말 가족 미션을 칸마다 담은 한 장 빙고예요.',
    time: '20분',
    age: '전 연령',
    material: '온가족',
    suppliesDetail: '도안 1장 + 펜',
    imageUrl: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-violet-100 text-violet-800 border-violet-200',
    printQuery: '빙고|가족|게임|보드게임',
    steps: ['가족 빙고 도안을 인쇄해요.', '미션을 하나씩 해요.', '한 줄이 되면 보상을 해요.'],
  },
  {
    id: 'sol-38',
    situation: 'special',
    situationLabel: '🎉 특별한 날',
    title: '새해 소원 깃발',
    desc: '소원을 적어 걸어 두는 한 장 기념일 깃발이에요.',
    time: '15분',
    age: '만 4~7세',
    material: '파티',
    suppliesDetail: '도안 1장 + 색연필',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-violet-100 text-violet-800 border-violet-200',
    printQuery: '새해|깃발|시즌|기념일',
    steps: ['소원 깃발 도안을 인쇄해요.', '소원을 적고 색칠해요.', '창문에 걸어 기념해요.'],
  },
  {
    id: 'sol-39',
    situation: 'special',
    situationLabel: '🎉 특별한 날',
    title: '생일 카드 한 장',
    desc: '오려 접으면 바로 전하는 생일 카드 도안이에요.',
    time: '15분',
    age: '만 3~7세',
    material: '파티',
    suppliesDetail: '도안 1장 + 색연필',
    imageUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-violet-100 text-violet-800 border-violet-200',
    printQuery: '생일|카드|파티|기념일',
    steps: ['생일 카드 도안을 인쇄해요.', '색칠하고 접어요.', '주인공에게 전해요.'],
  },
  {
    id: 'sol-40',
    situation: 'special',
    situationLabel: '🎉 특별한 날',
    title: '명절 송편 색칠',
    desc: '명절 분위기를 한 장으로 채우는 시즌 색칠이에요.',
    time: '15분',
    age: '만 2~6세',
    material: '파티',
    suppliesDetail: '도안 1장 + 크레파스',
    imageUrl: 'https://images.unsplash.com/photo-1515488044360-fb630819f3ba?w=800&auto=format&fit=crop&q=80',
    badgeColor: 'bg-violet-100 text-violet-800 border-violet-200',
    printQuery: '명절|시즌|색칠|기념일',
    steps: ['명절 도안을 인쇄해요.', '가족과 함께 색칠해요.', '식탁 위에 올려 기념해요.'],
  },
]

export function getPlaySolutionsBySituation(id: SituationId) {
  return PLAY_SOLUTIONS.filter((item) => item.situation === id)
}

export function getPlaySolution(id: string | undefined) {
  return PLAY_SOLUTIONS.find((item) => item.id === id)
}

export function playRecipePath(situationId: SituationId, recipeId: string) {
  return `/situation/${situationId}/${recipeId}`
}

export function situationEmoji(id: SituationId) {
  return SITUATION_ITEMS.find((item) => item.id === id)?.emoji ?? '🏠'
}
